ci: fix the failure of goreleaser
The release workflow failed at v1.1.0.

https://github.com/bufbuild/protoc-gen-validate/releases/tag/v1.1.0

https://github.com/bufbuild/protoc-gen-validate/actions/runs/10252222901/job/28362117064

```
/opt/hostedtoolcache/goreleaser-action/2.1.0/x64/goreleaser release --rm-dist
  ⨯ command failed                                   error=unknown flag: --rm-dist
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.1.0/x64/goreleaser' failed with exit code 1
```

--rm-dist was deprecated.

https://goreleaser.com/deprecations/#-rm-dist

Furthermore, we need to add `version: 2`.

```console
$ goreleaser check
  • only configurations files on  version: 2  are supported, yours is  version: 0 , please update your configuration
```